export async function generateAnalysisPDF(result) {
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 18;
  const contentW = pageW - margin * 2;

  const purple = [83, 74, 183];
  const purpleLight = [237, 235, 254];
  const green = [34, 197, 94];
  const greenLight = [240, 253, 244];
  const red = [239, 68, 68];
  const redLight = [254, 242, 242];
  const gray800 = [31, 41, 55];
  const gray500 = [107, 114, 128];
  const gray100 = [243, 244, 246];
  const white = [255, 255, 255];
  const amber = [245, 158, 11];

  const scoreRGB = (s) => s >= 75 ? green : s >= 50 ? amber : red;
  const docEx = doc;

  const addFooter = (pageNum, total) => {
    doc.setFontSize(8);
    doc.setTextColor(...gray500);
    doc.text("Generated by CareerLens", margin, pageH - 10);
    doc.text(`Page ${pageNum} of ${total}`, pageW - margin, pageH - 10, { align: "right" });
    doc.setDrawColor(220, 220, 220);
    doc.line(margin, pageH - 14, pageW - margin, pageH - 14);
  };

  doc.setFillColor(...purple);
  doc.rect(0, 0, pageW, 44, "F");
  doc.setFontSize(22);
  doc.setTextColor(...white);
  doc.setFont("helvetica", "bold");
  doc.text("CareerLens Analysis Report", margin, 20);
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(210, 207, 255);
  doc.text(
    `Generated ${new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" })}`,
    margin, 29
  );
  doc.text(`Best match: ${result.jd_title}`, margin, 37);

  doc.setFillColor(...scoreRGB(result.match_score));
  doc.roundedRect(pageW - margin - 28, 8, 28, 28, 3, 3, "F");
  doc.setFontSize(18);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...white);
  doc.text(`${result.match_score}`, pageW - margin - 14, 22, { align: "center" });
  doc.setFontSize(7);
  doc.setFont("helvetica", "normal");
  doc.text("/100  Match", pageW - margin - 14, 29, { align: "center" });

  let y = 56;
  const halfW = (contentW - 6) / 2;

  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...gray800);
  doc.text("Overall Match Score", margin, y);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...scoreRGB(result.match_score));
  doc.text(`${result.match_score}/100`, margin + halfW, y, { align: "right" });
  y += 4;
  doc.setFillColor(...gray100);
  doc.roundedRect(margin, y, halfW, 5, 1, 1, "F");
  doc.setFillColor(...scoreRGB(result.match_score));
  doc.roundedRect(margin, y, (halfW * result.match_score) / 100, 5, 1, 1, "F");

  const col2x = margin + halfW + 6;
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...gray800);
  doc.text("ATS Score", col2x, y - 4);
  doc.setFont("helvetica", "normal");
  doc.setFontSize(8);
  doc.setTextColor(...scoreRGB(result.ats_score));
  doc.text(`${result.ats_score}/100`, col2x + halfW, y - 4, { align: "right" });
  doc.setFillColor(...gray100);
  doc.roundedRect(col2x, y, halfW, 5, 1, 1, "F");
  doc.setFillColor(...scoreRGB(result.ats_score));
  doc.roundedRect(col2x, y, (halfW * result.ats_score) / 100, 5, 1, 1, "F");
  y += 14;

  doc.setFillColor(...purpleLight);
  const summaryLines = doc.splitTextToSize(result.summary, contentW - 8);
  const summaryH = summaryLines.length * 5.5 + 12;
  doc.roundedRect(margin, y, contentW, summaryH, 3, 3, "F");
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(...purple);
  doc.text("SUMMARY", margin + 4, y + 7);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(55, 48, 163);
  doc.text(summaryLines, margin + 4, y + 13);
  y += summaryH + 8;

  autoTable(doc, {
    startY: y,
    head: [["#", "Strong Point"]],
    body: result.strong_points.map((p, i) => [`${i + 1}`, p]),
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 3, textColor: gray800, overflow: "linebreak" },
    headStyles: { fillColor: green, textColor: white, fontStyle: "bold", fontSize: 9 },
    alternateRowStyles: { fillColor: greenLight },
    columnStyles: { 0: { cellWidth: 9, halign: "center", fontStyle: "bold" } },
  });
  y = docEx.lastAutoTable.finalY + 8;

  if (y > pageH - 80) { doc.addPage(); y = 20; }
  autoTable(doc, {
    startY: y,
    head: [["#", "Area for Improvement"]],
    body: result.weak_points.map((p, i) => [`${i + 1}`, p]),
    margin: { left: margin, right: margin },
    styles: { fontSize: 8.5, cellPadding: 3, textColor: gray800, overflow: "linebreak" },
    headStyles: { fillColor: red, textColor: white, fontStyle: "bold", fontSize: 9 },
    alternateRowStyles: { fillColor: redLight },
    columnStyles: { 0: { cellWidth: 9, halign: "center", fontStyle: "bold" } },
  });
  y = docEx.lastAutoTable.finalY + 8;

  if (result.ats_tips?.length > 0) {
    if (y > pageH - 70) { doc.addPage(); y = 20; }
    autoTable(doc, {
      startY: y,
      head: [["ATS Improvement Tips"]],
      body: result.ats_tips.map((t) => [t]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 3, textColor: gray800, overflow: "linebreak" },
      headStyles: { fillColor: [245, 158, 11], textColor: white, fontStyle: "bold", fontSize: 9 },
      alternateRowStyles: { fillColor: [255, 251, 235] },
    });
    y = docEx.lastAutoTable.finalY + 8;
  }

  if (result.per_jd_scores?.length > 0) {
    if (y > pageH - 70) { doc.addPage(); y = 20; }
    doc.setFontSize(11);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(...gray800);
    doc.text("Per-JD Score Breakdown", margin, y);
    y += 6;
    autoTable(doc, {
      startY: y,
      head: [["Role", "Company", "Score", "Key Match", "Key Gap"]],
      body: result.per_jd_scores.map((s) => [s.title, s.company, `${s.score}/100`, s.key_match, s.key_gap]),
      margin: { left: margin, right: margin },
      styles: { fontSize: 8, cellPadding: 3, textColor: gray800, overflow: "linebreak" },
      headStyles: { fillColor: purple, textColor: white, fontStyle: "bold", fontSize: 8.5 },
      alternateRowStyles: { fillColor: purpleLight },
      columnStyles: { 0: { cellWidth: 35 }, 1: { cellWidth: 28 }, 2: { cellWidth: 18, halign: "center", fontStyle: "bold" } },
      didParseCell: (data) => {
        if (data.column.index === 2 && data.section === "body") {
          const score = parseInt(String(data.cell.raw));
          data.cell.styles.textColor = scoreRGB(score);
        }
      },
    });
    y = docEx.lastAutoTable.finalY + 8;
  }

  if (result.keywords?.length > 0) {
    if (y > pageH - 70) { doc.addPage(); y = 20; }
    const present = result.keywords.filter((k) => k.in_cv).map((k) => k.word);
    const missing = result.keywords.filter((k) => !k.in_cv).map((k) => k.word);
    autoTable(doc, {
      startY: y,
      head: [["✓ Present in CV", "✗ Missing from CV"]],
      body: [[present.join(", ") || "—", missing.join(", ") || "—"]],
      margin: { left: margin, right: margin },
      styles: { fontSize: 8.5, cellPadding: 4, textColor: gray800, overflow: "linebreak" },
      headStyles: { fillColor: [55, 65, 81], textColor: white, fontStyle: "bold", fontSize: 9 },
      didParseCell: (data) => {
        if (data.section === "body") {
          data.cell.styles.textColor = data.column.index === 0
            ? [22, 163, 74]
            : [220, 38, 38];
        }
      },
    });
  }

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addFooter(p, totalPages);
  }

  doc.save(`cv-analysis-${Date.now()}.pdf`);
}
